Adding support for inventories from StorageDrawers mod.
blay09/CookingForBlockheads pull request #272
Opened 2018-03-29 07:41 UTC by Vlaeh

The feature consist in:
- adding KitchenItemProvider capability to drawers blocks,
- adding KitchenConnector capability to controllers and slave controllers blocks

It is to note that controllers from StorageDrawers have a 5 second refresh delay which makes them not suitable to be directly used as item providers.

I tested the this feature with both Minecraft 1.12 and 1.10 versions.

2018-03-29 09:27 UTC, BlayTheNinth requested changes

2018-03-29 09:27 UTC, blay09 commented on src/main/java/net/blay09/mods/cookingforblockheads/compat/CompatCapabilityLoader.java
> +    private final static CompatCapabilityLoader loader = new CompatCapabilityLoader();
This instance and the `register()` method isn't necessary, you can use the `@Mod.EventBusSubscriber` annotation with `modid` parameter to have the class itself be registered (the event handler will need to be static as well then).

2018-03-29 09:27 UTC, blay09 commented on src/main/java/net/blay09/mods/cookingforblockheads/compat/CompatCapabilityLoader.java
> +    private final static ResourceLocation capabilityKitchenConnector = new ResourceLocation(CookingForBlockheads.MOD_ID, CapabilityKitchenItemProvider.CAPABILITY.getName());
Wrong name being used for the kitchen connector.

2018-03-29 09:27 UTC, blay09 commented on src/main/java/net/blay09/mods/cookingforblockheads/compat/CompatCapabilityLoader.java
> +                CookingForBlockheads.logger.warn("Incompatible TileEntity class: {}", className);
Single-liners should get braces too.

2018-03-29 09:27 UTC, blay09 commented on src/main/java/net/blay09/mods/cookingforblockheads/compat/CompatCapabilityLoader.java
> +                    new ICapabilityProvider() {
This should be extracted into a private static class for better readability.

2018-03-29 09:27 UTC, blay09 commented on src/main/java/net/blay09/mods/cookingforblockheads/compat/CompatCapabilityLoader.java
> +                else if (entity instanceof IItemHandler)
This `else if` shouldn't be necessary, the correct implementation is to return item handlers as a capability, not implement them on the tile entity.

2018-03-29 09:27 UTC, blay09 commented on src/main/java/net/blay09/mods/cookingforblockheads/compat/CompatCapabilityLoader.java
> +        return new ICapabilityProvider() {
This should also be extracted into a private static class, and be called `createItemCapabilityProvider` (typo)

2018-03-29 09:27 UTC, blay09 commented on src/main/java/net/blay09/mods/cookingforblockheads/compat/CompatCapabilityLoader.java
> +                if (itemHandler != null)
I assume the item handler is being stored to allow re-checking for the capability if none was found previously. I think a `boolean foundItemHandler` would be more obvious though, currently the null-check looks weird (null-checking one thing, then returning another).

2018-03-29 09:27 UTC, blay09 commented on src/main/java/net/blay09/mods/cookingforblockheads/compat/CompatCapabilityLoader.java
> +                if (kitchenProvider == null)
This could be moved below the if below it and fed the correct `IItemHandler` right away in the constructor.

2018-03-29 09:27 UTC, blay09 commented on src/main/java/net/blay09/mods/cookingforblockheads/compat/CompatCapabilityLoader.java
> +            if (! c.isInstance(entity))
I think it's fine to just check the exact class via `contains(entity.getClass())` - probably safer too, in case a mod ends up adding a sub-class that may not be compatible in the way the parent class was.

2018-03-29 09:27 UTC, blay09 commented on src/main/java/net/blay09/mods/cookingforblockheads/compat/CompatCapabilityLoader.java
> +    private final static ItemStackHandler emptyItemHandler = new ItemStackHandler(0);
This should override the insert method to refuse insertion of items (can be done in an anonymous class in this case), otherwise there's risk of item deletion in the future, for example if #150 gets implemented.

2018-03-29 09:28 UTC, blay09 commented
What does `DynamicKitchenItemProvider` do different and where would it be needed?

2018-03-29 17:32 UTC, Vlaeh commented on src/main/java/net/blay09/mods/cookingforblockheads/compat/CompatCapabilityLoader.java
> +    private final static CompatCapabilityLoader loader = new CompatCapabilityLoader();
Idea here is to register only if we are expecting entities to be caught: if "storagedrawers" is not loaded, CookingForBlockhead will not be registered and not be called for every TileEntity created.

2018-03-29 17:38 UTC, Vlaeh commented on src/main/java/net/blay09/mods/cookingforblockheads/compat/CompatCapabilityLoader.java
> +                else if (entity instanceof IItemHandler)
True :) This is a remaining of my tests with Bibliocraft (which does implement the item handler in the tile entity -- clearly not something to do). I will remove it.

2018-03-29 17:40 UTC, Vlaeh commented on src/main/java/net/blay09/mods/cookingforblockheads/compat/CompatCapabilityLoader.java
> +            if (! c.isInstance(entity))
I agree, and this will allow usage of a HashSet to store classes, which will be faster when calling contains.

2018-03-29 17:41 UTC, blay09 commented on src/main/java/net/blay09/mods/cookingforblockheads/compat/CompatCapabilityLoader.java
> +    private final static CompatCapabilityLoader loader = new CompatCapabilityLoader();
Hmm, okay, I guess that makes sense.

2018-03-29 17:49 UTC, Vlaeh commented
I used the `DynamicKitchenItemProvider` to attach KitchenItemProvider capability to StorageDrawers Controllers. Those blocks have a dynamic content, the getSlots() can grow (when new Drawers are added); this created `ArrayIndexOutOfBoundsException` in KitchenItemProvider as the `usedStackSize` is fixed when setHandler is called.
I can remove this private class as it is no longer needed for the StorageDrawer support.

2018-04-01 09:36 UTC, Vlaeh commented
Finished testing new changes, hoping I covered all comments.
Current code is working fine with first release of StorageDrawers (1.12-5.2.9) and last one too (1.12.2-5.3.6).

2018-04-03 07:27 UTC, BlayTheNinth approved these changes

2018-04-03 07:27 UTC, merged

2018-04-03 07:28 UTC, blay09 commented
Thanks, will be putting this out in the next release.

2018-06-20 06:24 UTC, dragonshardz commented
Is it possible to make connections to Storage Drawer arrays also possible through Storage Drawer Trim blocks, and not only by having CFB blocks right next to a full drawer?

2018-06-20 07:23 UTC, Vlaeh commented
Yes, Storage Drawer Trim blocks can be used to connect a Storage Drawer array to CFB.

2018-08-23 07:51 UTC, Vlaeh commented
Hi, sorry for the long delay.
Playing with latest FTB Revelation pack showed that the Trim blocks are not connecting as intended.
I'll have a look at it.
As long as it is not corrected, I recommend using empty drawers to link to a storage drawers array.

2018-09-04 15:13 UTC, Vlaeh commented
Hi,

Unfortunately, after digging into the implementation, it is normal that Storage Drawer Trim blocks are not working as I thought they would.
kitchen connections are made using capabilities, and capabilities can only be attached to tile entities.
Storage Drawer provides 2 kinds of Trim blocks:
- Wood Trim blocks (crafted using crafting table): they are pure plain blocks and do not implement Tile Entities.
- Framed Trim blocks (crafted using Storage Drawers Framing Table): those blocks do implement Tile Entities and can be used to connect Storage Drawers 

@blay09, I see different ways to deal with that:
- Documenting plain wood Trim blocks as not usable to connect a Storage Drawers array
- Making an enhancement request to Storage Drawers so that wood Trim blocks implement Tile Entities.
- Creating a configurable registry of blocks' types that will be used by findNeighbourKitchenBlocks() (it will be initialized with ModBlocks.kitchenFloor).

Vlaeh

2018-09-04 17:56 UTC, blay09 commented
Supporting non-TE blocks in some registry is the only sensible solution really. The kitchen floor already works like that, so might as well expose it to the compat loader.

2018-09-04 20:58 UTC, Vlaeh commented
Great, I will work on having a registry and submit a new pull request when ready.