Allow block coloring with any oredict dye (fixes #381)
blay09/CookingForBlockheads pull request #402
Opened 2019-10-04 13:32 UTC by WesCook

Also prevents the dye from being consumed in creative mode.

2019-10-04 13:48 UTC, Skydragonsz approved these changes

2019-10-04 13:48 UTC, Skydragonsz commented on src/main/java/net/blay09/mods/cookingforblockheads/block/BlockOven.java
> +        /*if (!heldItem.isEmpty() && DyeUtils.isDye(heldItem)) {
Why is this in comments? 
Doesn't this also fix #401?

2019-10-04 13:56 UTC, WesCook commented on src/main/java/net/blay09/mods/cookingforblockheads/block/BlockOven.java
> +        /*if (!heldItem.isEmpty() && DyeUtils.isDye(heldItem)) {
The original was in comments, so I left it commented out.  I only updated it to support dyes along with the other blocks.

2019-10-05 15:48 UTC, BlayTheNinth requested changes

2019-10-05 15:48 UTC, blay09 commented on src/main/java/net/blay09/mods/cookingforblockheads/block/BlockCookingTable.java
> +                        if (!player.isCreative()) {
These `isCreative()` checks should be replaced by `if (!player.capabilities.isCreativeMode) {` to match Vanilla, as there the item consumption is tied to the capabilities rather than the gamemode itself.

2019-10-05 15:48 UTC, blay09 commented on src/main/java/net/blay09/mods/cookingforblockheads/block/BlockOven.java
> +        /*if (!heldItem.isEmpty() && DyeUtils.isDye(heldItem)) {
Yes, dyeing the oven by tint looked ugly so I left it disabled a while back. I'll be looking at proper oven dyeing in 1.14.4.

2019-10-05 16:20 UTC, merged